sample_app_master/sample_app_master/sample_app-master/config/routes.rb
Rails.application.routes.draw do

 root 'sample_app#sample_app/home'

  get 'sample_app/home'
  get 'sample_app/help'
  get 'sample_app/login'
  get 'sample_app/about'
  get 'sample_app/contact'

end

sample_app_master/sample_app_master/sample_app-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sample_app_master/sample_app_master/sample_app-master/app/controllers/sample_app_controller.rb
class SampleAppController < ApplicationController
	def home

	end
	def contact
		
	end
	def about
		
	end
	def help
		
	end
	def login
		
	end
end

sample_app_master/sample_app_master/sample_app-master/app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else 
			"#{page_title} | #{base_title}"	
		end
	end
end

sample_app_master/sample_app_master/sample_app-master/app/helpers/sample_app_helper.rb
module SampleAppHelper

end

sample_app_master/sample_app_master/sample_app-master/app/views/layouts/_footer.html.erb
<footer>
	<div class="footer-wrap">
		<%= link_to image_tag("Ruby_on_Rails.png", :alt => "Rails logo", :class => "img-class"), 'http://rubyonrails.org/' %>
	</div>
</footer>

sample_app_master/sample_app_master/sample_app-master/app/views/layouts/_header.html.erb
<header>
	<div class="header-wrap">
		<div class="header-right">
			<nav>
				<%= link_to "Home  ", sample_app_home_path, class:"link" %>"|"
				<%= link_to " About  ", sample_app_about_path, class:"link" %>"|"
				<%= link_to " Contact  ", sample_app_contact_path, class:"link" %>"|"
				<%= link_to " Help ", sample_app_help_path, class:"link" %>"|"
				<%= link_to " Login", sample_app_login_path, class:"link" %>
			</nav>
		</div>
		<div class="header-left"><%= link_to "Sample App", sample_app_home_path, class:"link" %></div>	
	</div>
</header>

sample_app_master/sample_app_master/sample_app-master/app/views/sample_app/about.html.erb
<% provide(:title,"About") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag "custom.css" %>
</head>
<body>
<%= yield %>
<%= render 'layouts/header' %>
<div class="content">
	<div class="content-wrap">
		<p class="p1">Welcome to the About Sample App</p>
		<div class="content-about">
			<p>
			References : <br />
			Ruby on Rails Tutorial: <a href="http://www.railstutorial.org/"><em>http://www.railstutorial.org/</em></a><br />
			Ruby on Rails Books: <a href="http://www.railstutorial.org/book"><em>http://www.railstutorial.org/book</em></a><br />
			Screencast Series :  <a href="http://screencasts.railstutorial.org/"><em>http://screencasts.railstutorial.org/</em></a><br />
			Ruby on Rails: <a href="http://rubyonrails.org/"><em>http://rubyonrails.org/</em></a>
			</p>
		</div>
	</div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

sample_app_master/sample_app_master/sample_app-master/app/views/sample_app/contact.html.erb
<% provide(:title,"Contact") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag "custom.css" %>
</head>
<body>
<%= yield %>
<%= render 'layouts/header' %>
<div class="content">
	<div class="content-wrap">
		<p class="p1">Welcome to the contact Sample App</p>
		<p>You can contact me via email: <a href="https://github.com/doanxuanhuy93/"><em>https://github.com/doanxuanhuy93/</em></a></p>		
	</div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

sample_app_master/sample_app_master/sample_app-master/app/views/sample_app/help.html.erb
<% provide(:title,"Help") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag "custom.css" %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="content">
	<div class="content-wrap">
		<p class="p1">Welcome to the Help Sample App</p>
		<p>
		  Get help on the Ruby on Rails Tutorial at the
		  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.<br />
		  To get help on this sample app, see the
		  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
		  book</a>.
		</p>
	</div>
</div>		
<%= render 'layouts/footer' %>
</body>
</html>

sample_app_master/sample_app_master/sample_app-master/app/views/sample_app/home.html.erb
<% provide(:title,"Home") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag "custom.css" %>
</head>
<body>
<%= yield %>
<%= render 'layouts/header' %>
<div class="content">
	<div class="content-wrap">
		<p class="p1">Welcome to the Home Sample App</p>
		<h6>This is the home page for the <a href="http://www.railstutorial.org">Ruby on Rails Tutorial</a> sample application</h6>
		<%= button_to "Sign up now!", sample_app_login_path, :class =>"button-class", :method => "get" %>
	</div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

sample_app_master/sample_app_master/sample_app-master/app/views/sample_app/login.html.erb
<% provide(:title,"Login") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag "custom.css" %>
</head>
<body>
<%= yield %>
<%= render 'layouts/header' %>
<div class="content">
	<div class="content-wrap">
		<p class="p1">Welcome to the Login Sample App</p>
		<p>Thank you for login.</p>
	</div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>